version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    restart: always
    container_name: django
    image: hr_crm_django
    volumes:
      - ./static:/app/static
    depends_on:
      - postgres
    env_file:
      - .envs/.django
      - .envs/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    restart: always
    container_name: postgres
    image: hr_crm_postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres_backups:/backups
    env_file:
      - .envs/.postgres

  caddy:
    build:
      context: .
      dockerfile: ./compose/caddy/Dockerfile
    restart: always
    container_name: caddy
    image: hr_crm_caddy
    depends_on:
      - django
    volumes:
      - ./caddy:/root/.caddy
      - ./static:/app/static
      - ../FrontJS/build:/www/reachthestars.ml
    env_file:
      - .envs/.caddy
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "2015:2015"

  rabbitmq:
    build: compose/rabbitmq
    container_name: rabbitmq
    image: hr_crm_rabbitmq
    ports:
      - "15673:15672"
      - "5673:5672"
    volumes:
      - /opt/rabbitmq:/var/lib/rabbitmq